"""Report renderers — Markdown and HTML output for job match reports.

Reports are split into two sections:
  1. 🌍 Remote Jobs — sorted by date posted (newest first)
  2. 🏢 Non-Remote Jobs — sorted by date posted (newest first)
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from src.models.job import JobModel

logger = logging.getLogger(__name__)


# =============================================================================
# Markdown renderer
# =============================================================================


def render_markdown(
    remote_jobs: list[JobModel],
    non_remote_jobs: list[JobModel],
    stats: dict | None = None,
) -> str:
    """Render a Markdown report with Remote and Non-Remote sections."""
    stats = stats or {}
    lines: list[str] = []

    run_date = stats.get("run_date", datetime.now().strftime("%Y-%m-%d"))
    mode = stats.get("mode", "daily")

    lines.append(f"# Job Search Results — {run_date} ({mode})")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append(f"- **Total fetched**: {stats.get('total_fetched', 0)}")
    lines.append(f"- **Keyword annotated**: {stats.get('total_filtered', 0)}")
    lines.append(f"- **Top scored**: {stats.get('total_matched', 0)}")
    lines.append(f"- **Showing**: {stats.get('total_showing', len(remote_jobs) + len(non_remote_jobs))}")
    lines.append(f"  - 🌍 Remote: {stats.get('total_remote', len(remote_jobs))}")
    lines.append(f"  - 🏢 Non-Remote: {stats.get('total_non_remote', len(non_remote_jobs))}")
    lines.append("")

    all_jobs = remote_jobs + non_remote_jobs
    if not all_jobs:
        lines.append("*No jobs were fetched — check your sources.yaml configuration.*")
        return "\n".join(lines)

    # Section 1: Remote Jobs
    if remote_jobs:
        lines.append(f"## 🌍 Remote Jobs ({len(remote_jobs)})")
        lines.append("")
        _render_md_job_list(lines, remote_jobs)

    # Section 2: Non-Remote Jobs
    if non_remote_jobs:
        lines.append(f"## 🏢 Non-Remote Jobs ({len(non_remote_jobs)})")
        lines.append("")
        _render_md_job_list(lines, non_remote_jobs)

    # Footer
    lines.append("---")
    lines.append(f"*Generated by Job Search Agent on {run_date}*")

    return "\n".join(lines)


def _render_md_job_list(lines: list[str], jobs: list[JobModel]) -> None:
    """Render a list of jobs as Markdown entries."""
    for i, job in enumerate(jobs, 1):
        lines.append(f"### {i}. {job.title}")
        lines.append(f"**{job.company}**")
        if job.location:
            lines.append(f"📍 {job.location} | {job.remote_type.value}")
        else:
            lines.append(f"📍 {job.remote_type.value}")

        if job.posted_date:
            lines.append(f"📅 {job.posted_date[:10]}")

        if job.salary_text:
            lines.append(f"💰 {job.salary_text}")
        elif "missing_salary" in job.flags:
            lines.append("💰 *Salary not specified*")

        lines.append(f"⭐ Score: {job.llm_score or 'N/A'}/10 (confidence: {job.llm_confidence or 'N/A'})")

        if job.reputation_score is not None:
            lines.append(f"🏢 Company reputation: {job.reputation_score}/10")

        lines.append(f"🔗 [Apply]({job.url})")

        if job.llm_reasons:
            lines.append("")
            lines.append("**Why matched:**")
            for reason in job.llm_reasons:
                lines.append(f"- {reason}")

        if job.flags:
            flags_display = [f for f in job.flags if f != "missing_salary"]
            if flags_display:
                lines.append(f"⚠️ Flags: {', '.join(flags_display)}")

        lines.append("")
        lines.append("---")
        lines.append("")


# =============================================================================
# HTML renderer
# =============================================================================


def render_html(
    remote_jobs: list[JobModel],
    non_remote_jobs: list[JobModel],
    stats: dict | None = None,
) -> str:
    """Render an HTML email report with Remote and Non-Remote sections."""
    stats = stats or {}
    run_date = stats.get("run_date", datetime.now().strftime("%Y-%m-%d"))
    mode = stats.get("mode", "daily")
    total_showing = stats.get("total_showing", len(remote_jobs) + len(non_remote_jobs))

    html_parts: list[str] = []
    html_parts.append("""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px; color: #1a1a1a; background: #f9f9f9; }
  .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 24px; border-radius: 12px; margin-bottom: 24px; }
  .header h1 { margin: 0; font-size: 22px; }
  .header p { margin: 8px 0 0; opacity: 0.9; }
  .stats { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin-bottom: 24px; }
  .stat-card { background: white; padding: 16px; border-radius: 8px; border: 1px solid #e0e0e0; }
  .stat-card .label { font-size: 12px; color: #666; text-transform: uppercase; }
  .stat-card .value { font-size: 24px; font-weight: 700; color: #333; }
  .section-header { background: #f0f0f0; padding: 14px 20px; border-radius: 8px; margin: 24px 0 16px; font-size: 18px; font-weight: 700; }
  .section-header.remote { background: #d4edda; color: #155724; }
  .section-header.non-remote { background: #cce5ff; color: #004085; }
  .job-card { background: white; border: 1px solid #e0e0e0; border-radius: 10px; padding: 20px; margin-bottom: 16px; }
  .job-card h3 { margin: 0 0 6px; font-size: 17px; }
  .job-card .company { color: #555; font-weight: 600; margin-bottom: 8px; }
  .job-card .meta { font-size: 13px; color: #777; margin-bottom: 8px; }
  .job-card .score { display: inline-block; background: #f0f0f0; padding: 4px 10px; border-radius: 20px; font-size: 13px; font-weight: 600; }
  .score-high { background: #d4edda; color: #155724; }
  .score-med { background: #fff3cd; color: #856404; }
  .score-low { background: #f8d7da; color: #721c24; }
  .reasons { margin-top: 10px; padding-left: 18px; font-size: 13px; color: #555; }
  .reasons li { margin-bottom: 4px; }
  .apply-btn { display: inline-block; margin-top: 12px; padding: 8px 18px; background: #667eea; color: white !important; text-decoration: none; border-radius: 6px; font-size: 13px; font-weight: 600; }
  .footer { text-align: center; font-size: 12px; color: #999; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; }
  .no-results { text-align: center; padding: 40px; color: #999; }
  .flags { font-size: 12px; color: #e67e22; margin-top: 6px; }
</style>
</head>
<body>
""")

    # Header
    html_parts.append(f"""
<div class="header">
  <h1>🔍 Daily Agentic AI Job Matches</h1>
  <p>{run_date} &mdash; {mode} mode &mdash; {total_showing} jobs</p>
</div>
""")

    # Stats grid
    html_parts.append(f"""
<div class="stats">
  <div class="stat-card"><div class="label">Fetched</div><div class="value">{stats.get('total_fetched', 0)}</div></div>
  <div class="stat-card"><div class="label">Annotated</div><div class="value">{stats.get('total_filtered', 0)}</div></div>
  <div class="stat-card"><div class="label">🌍 Remote</div><div class="value">{stats.get('total_remote', len(remote_jobs))}</div></div>
  <div class="stat-card"><div class="label">🏢 Non-Remote</div><div class="value">{stats.get('total_non_remote', len(non_remote_jobs))}</div></div>
</div>
""")

    all_jobs = remote_jobs + non_remote_jobs
    if not all_jobs:
        html_parts.append('<div class="no-results">No jobs were fetched — check your sources.yaml configuration.</div>')
    else:
        # Section 1: Remote Jobs
        if remote_jobs:
            html_parts.append(f'<div class="section-header remote">🌍 Remote Jobs ({len(remote_jobs)})</div>')
            _render_html_job_list(html_parts, remote_jobs)

        # Section 2: Non-Remote Jobs
        if non_remote_jobs:
            html_parts.append(f'<div class="section-header non-remote">🏢 Non-Remote / Hybrid / Onsite ({len(non_remote_jobs)})</div>')
            _render_html_job_list(html_parts, non_remote_jobs)

    # Footer
    html_parts.append(f"""
<div class="footer">
  Generated by Job Search Agent on {run_date} &mdash; sorted by date posted (newest first)
</div>
</body>
</html>
""")

    return "".join(html_parts)


def _render_html_job_list(html_parts: list[str], jobs: list[JobModel]) -> None:
    """Render a list of job cards as HTML."""
    for i, job in enumerate(jobs, 1):
        score = job.llm_score or 0
        score_class = "score-high" if score >= 8 else "score-med" if score >= 6 else "score-low"

        salary_line = ""
        if job.salary_text:
            salary_line = f"💰 {job.salary_text} &nbsp; "
        elif "missing_salary" in job.flags:
            salary_line = "💰 <em>Salary not specified</em> &nbsp; "

        location_line = job.location or job.remote_type.value
        date_line = job.posted_date[:10] if job.posted_date else "Unknown"

        reasons_html = ""
        if job.llm_reasons:
            reasons_html = "<ul class='reasons'>" + "".join(
                f"<li>{r}</li>" for r in job.llm_reasons
            ) + "</ul>"

        flags_html = ""
        flags_display = [f for f in job.flags if f != "missing_salary"]
        if flags_display:
            flags_html = f'<div class="flags">⚠️ {", ".join(flags_display)}</div>'

        rep_html = ""
        if job.reputation_score is not None:
            rep_html = f" &nbsp; 🏢 Rep: {job.reputation_score}/10"

        html_parts.append(f"""
<div class="job-card">
  <h3>{i}. {_html_escape(job.title)}</h3>
  <div class="company">{_html_escape(job.company)}</div>
  <div class="meta">
    📍 {_html_escape(location_line)} &nbsp; 📅 {date_line} &nbsp; {salary_line}
  </div>
  <span class="score {score_class}">⭐ {score}/10</span>{rep_html}
  {reasons_html}
  {flags_html}
  <a href="{job.url}" class="apply-btn">View &amp; Apply →</a>
</div>
""")


# =============================================================================
# Save
# =============================================================================


def save_report(md_content: str, html_content: str, run_date: str) -> None:
    """Save report files to reports/ directory."""
    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)

    md_path = reports_dir / f"{run_date}.md"
    html_path = reports_dir / f"{run_date}.html"

    md_path.write_text(md_content, encoding="utf-8")
    html_path.write_text(html_content, encoding="utf-8")

    logger.info("Reports saved: %s, %s", md_path, html_path)


def _html_escape(text: str) -> str:
    """Basic HTML escaping."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
